### ISSUE TITLE
Use CLIc for OpenCL runtime initializion

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/ITKCLEsperanto#13]

**Comment by thewtex** [comment]
From the current instantiation template filter (remove from the repository), perform the setup in 

- itkOpenCLSetup
- itkOpenCLDataManager

and related classes, by porting from elastix:

https://github.com/SuperElastix/elastix/tree/develop/Common/OpenCL
https://github.com/SuperElastix/elastix/tree/develop/Common/OpenCL/ITKimprovements

Port related tests in elastix, ITK:

https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/Core/GPUCommon/include
https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/Core/GPUCommon/test

**Comment by thewtex** [comment]
Possibly first:

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/GPUCommon/include/itkGPUContextManager.h

uses a CLIc instance.

**Comment by thewtex** [comment]
@aaron-bray done?

**Comment by aaron-bray** [comment]
This is complete
We are able to execute OpenCL kernels provided by and using the CLIc API
