### ISSUE TITLE
Tag PyPI Wheels

### ISSUE THREAD

**Issue by tbirdso** [InsightSoftwareConsortium/ITKCLEsperanto#36]
## Prerequisites

GPU test failure resolved (depends on https://github.com/InsightSoftwareConsortium/ITKCLEsperanto/issues/31)

## Steps

- Tag version in Github
- Will likely need to manually upload first wheel artifacts to PyPI, subsequent tags will upload automatically. See [https://itkpythonpackage.readthedocs.io/en/master/Build_ITK_Module_Python_packages.html#upload-the-packages-to-pypi](https://itkpythonpackage.readthedocs.io/en/master/Build_ITK_Module_Python_packages.html#upload-the-packages-to-pypi) for instructions.
- Once PyPI packages are uploaded, new version uploads from CI can be automated. See https://itkpythonpackage.readthedocs.io/en/master/Build_ITK_Module_Python_packages.html#automate-pypi-package-uploads

**Comment by tbirdso** [comment]
ITKCLEsperanto tagged `v0.2.1` packages are now available at https://pypi.org/project/itk-clesperanto/.

To use:
```
> pip install itk-clesperanto
> python
>>> import itk
>>> image = itk.CLEImage[<pixel type>, <dimension>].New()
...
```

cc @thewtex @aaron-bray

**Comment by thewtex** [comment]
@tbirdso AWESOME! Well done 👏 ✔️ 👍
